//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Ethnicity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Gender" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BirthDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BirthDateVerification" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}PlaceOfBirth" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CountyOfBirth" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StateOfBirth" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CountryOfBirth" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CountryOfCitizenship" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CountryOfResidency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CountryArrivalDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CitizenshipStatus" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EnglishProficiency" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Language" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}DwellingArrangement" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}MaritalStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ethnicity",
    "gender",
    "birthDate",
    "birthDateVerification",
    "placeOfBirth",
    "countyOfBirth",
    "stateOfBirth",
    "countryOfBirth",
    "countryOfCitizenship",
    "countryOfResidency",
    "countryArrivalDate",
    "citizenshipStatus",
    "englishProficiency",
    "language",
    "dwellingArrangement",
    "maritalStatus"
})
@XmlRootElement(name = "Demographics")
public class Demographics {

    @XmlElement(name = "Ethnicity", required = true)
    protected List<Ethnicity> ethnicity;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "BirthDate")
    protected String birthDate;
    @XmlElement(name = "BirthDateVerification")
    protected String birthDateVerification;
    @XmlElement(name = "PlaceOfBirth")
    protected String placeOfBirth;
    @XmlElement(name = "CountyOfBirth")
    protected String countyOfBirth;
    @XmlElement(name = "StateOfBirth")
    protected StateOfBirth stateOfBirth;
    @XmlElement(name = "CountryOfBirth")
    protected CountryOfBirth countryOfBirth;
    @XmlElement(name = "CountryOfCitizenship", required = true)
    protected List<CountryOfCitizenship> countryOfCitizenship;
    @XmlElement(name = "CountryOfResidency", required = true)
    protected List<CountryOfResidency> countryOfResidency;
    @XmlElement(name = "CountryArrivalDate")
    protected String countryArrivalDate;
    @XmlElement(name = "CitizenshipStatus")
    protected String citizenshipStatus;
    @XmlElement(name = "EnglishProficiency")
    protected EnglishProficiency englishProficiency;
    @XmlElement(name = "Language", required = true)
    protected List<Language> language;
    @XmlElement(name = "DwellingArrangement")
    protected String dwellingArrangement;
    @XmlElement(name = "MaritalStatus")
    protected String maritalStatus;

    /**
     * Gets the value of the ethnicity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ethnicity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEthnicity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ethnicity }
     * 
     * 
     */
    public List<Ethnicity> getEthnicity() {
        if (ethnicity == null) {
            ethnicity = new ArrayList<Ethnicity>();
        }
        return this.ethnicity;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthDateVerification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDateVerification() {
        return birthDateVerification;
    }

    /**
     * Sets the value of the birthDateVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDateVerification(String value) {
        this.birthDateVerification = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfBirth(String value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the countyOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountyOfBirth() {
        return countyOfBirth;
    }

    /**
     * Sets the value of the countyOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountyOfBirth(String value) {
        this.countyOfBirth = value;
    }

    /**
     * Gets the value of the stateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link StateOfBirth }
     *     
     */
    public StateOfBirth getStateOfBirth() {
        return stateOfBirth;
    }

    /**
     * Sets the value of the stateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateOfBirth }
     *     
     */
    public void setStateOfBirth(StateOfBirth value) {
        this.stateOfBirth = value;
    }

    /**
     * Gets the value of the countryOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link CountryOfBirth }
     *     
     */
    public CountryOfBirth getCountryOfBirth() {
        return countryOfBirth;
    }

    /**
     * Sets the value of the countryOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryOfBirth }
     *     
     */
    public void setCountryOfBirth(CountryOfBirth value) {
        this.countryOfBirth = value;
    }

    /**
     * Gets the value of the countryOfCitizenship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryOfCitizenship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountryOfCitizenship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryOfCitizenship }
     * 
     * 
     */
    public List<CountryOfCitizenship> getCountryOfCitizenship() {
        if (countryOfCitizenship == null) {
            countryOfCitizenship = new ArrayList<CountryOfCitizenship>();
        }
        return this.countryOfCitizenship;
    }

    /**
     * Gets the value of the countryOfResidency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryOfResidency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountryOfResidency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryOfResidency }
     * 
     * 
     */
    public List<CountryOfResidency> getCountryOfResidency() {
        if (countryOfResidency == null) {
            countryOfResidency = new ArrayList<CountryOfResidency>();
        }
        return this.countryOfResidency;
    }

    /**
     * Gets the value of the countryArrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryArrivalDate() {
        return countryArrivalDate;
    }

    /**
     * Sets the value of the countryArrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryArrivalDate(String value) {
        this.countryArrivalDate = value;
    }

    /**
     * Gets the value of the citizenshipStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitizenshipStatus() {
        return citizenshipStatus;
    }

    /**
     * Sets the value of the citizenshipStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitizenshipStatus(String value) {
        this.citizenshipStatus = value;
    }

    /**
     * Gets the value of the englishProficiency property.
     * 
     * @return
     *     possible object is
     *     {@link EnglishProficiency }
     *     
     */
    public EnglishProficiency getEnglishProficiency() {
        return englishProficiency;
    }

    /**
     * Sets the value of the englishProficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnglishProficiency }
     *     
     */
    public void setEnglishProficiency(EnglishProficiency value) {
        this.englishProficiency = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Language }
     * 
     * 
     */
    public List<Language> getLanguage() {
        if (language == null) {
            language = new ArrayList<Language>();
        }
        return this.language;
    }

    /**
     * Gets the value of the dwellingArrangement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDwellingArrangement() {
        return dwellingArrangement;
    }

    /**
     * Sets the value of the dwellingArrangement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDwellingArrangement(String value) {
        this.dwellingArrangement = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

}
