//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatePlaced" type="{http://www.sifinfo.org/infrastructure/1.x}DateOrEmptyType" minOccurs="0"/>
 *         &lt;element name="DateNeeded" type="{http://www.sifinfo.org/infrastructure/1.x}DateOrEmptyType" minOccurs="0"/>
 *         &lt;element name="MadeAvailable" type="{http://www.sifinfo.org/infrastructure/1.x}DateOrEmptyType" minOccurs="0"/>
 *         &lt;element name="Expires" type="{http://www.sifinfo.org/infrastructure/1.x}DateOrEmptyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Ready"/>
 *             &lt;enumeration value="NotReady"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datePlaced",
    "dateNeeded",
    "madeAvailable",
    "expires"
})
@XmlRootElement(name = "HoldInfo")
public class HoldInfo {

    @XmlElement(name = "DatePlaced")
    protected String datePlaced;
    @XmlElement(name = "DateNeeded")
    protected String dateNeeded;
    @XmlElement(name = "MadeAvailable")
    protected String madeAvailable;
    @XmlElement(name = "Expires")
    protected String expires;
    @XmlAttribute(name = "Type", required = true)
    protected String type;

    /**
     * Gets the value of the datePlaced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatePlaced() {
        return datePlaced;
    }

    /**
     * Sets the value of the datePlaced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatePlaced(String value) {
        this.datePlaced = value;
    }

    /**
     * Gets the value of the dateNeeded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateNeeded() {
        return dateNeeded;
    }

    /**
     * Sets the value of the dateNeeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateNeeded(String value) {
        this.dateNeeded = value;
    }

    /**
     * Gets the value of the madeAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMadeAvailable() {
        return madeAvailable;
    }

    /**
     * Sets the value of the madeAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMadeAvailable(String value) {
        this.madeAvailable = value;
    }

    /**
     * Gets the value of the expires property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpires() {
        return expires;
    }

    /**
     * Sets the value of the expires property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpires(String value) {
        this.expires = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
