//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Teacher" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SectionRoom" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}MeetingTime" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TermInfoRefId" use="required" type="{http://www.sifinfo.org/infrastructure/1.x}RefIdOrEmptyType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teacher",
    "sectionRoom",
    "meetingTime"
})
@XmlRootElement(name = "ScheduleInfo")
public class ScheduleInfo {

    @XmlElement(name = "Teacher", required = true)
    protected List<Teacher> teacher;
    @XmlElement(name = "SectionRoom", required = true)
    protected List<SectionRoom> sectionRoom;
    @XmlElement(name = "MeetingTime", required = true)
    protected List<MeetingTime> meetingTime;
    @XmlAttribute(name = "TermInfoRefId", required = true)
    protected String termInfoRefId;

    /**
     * Gets the value of the teacher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the teacher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeacher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Teacher }
     * 
     * 
     */
    public List<Teacher> getTeacher() {
        if (teacher == null) {
            teacher = new ArrayList<Teacher>();
        }
        return this.teacher;
    }

    /**
     * Gets the value of the sectionRoom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sectionRoom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSectionRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SectionRoom }
     * 
     * 
     */
    public List<SectionRoom> getSectionRoom() {
        if (sectionRoom == null) {
            sectionRoom = new ArrayList<SectionRoom>();
        }
        return this.sectionRoom;
    }

    /**
     * Gets the value of the meetingTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meetingTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeetingTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeetingTime }
     * 
     * 
     */
    public List<MeetingTime> getMeetingTime() {
        if (meetingTime == null) {
            meetingTime = new ArrayList<MeetingTime>();
        }
        return this.meetingTime;
    }

    /**
     * Gets the value of the termInfoRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermInfoRefId() {
        return termInfoRefId;
    }

    /**
     * Sets the value of the termInfoRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermInfoRefId(String value) {
        this.termInfoRefId = value;
    }

}
