//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CourseCodeOverride" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StateCourseCodeOverride" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}DistrictCourseCodeOverride" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SubjectAreaOverride" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CourseTitleOverride" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}InstructionalLevelOverride" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CourseCreditsOverride" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Override" use="required" type="{http://www.sifinfo.org/infrastructure/1.x}YesOrNoOrEmptyType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseCodeOverride",
    "stateCourseCodeOverride",
    "districtCourseCodeOverride",
    "subjectAreaOverride",
    "courseTitleOverride",
    "instructionalLevelOverride",
    "courseCreditsOverride"
})
@XmlRootElement(name = "SchoolCourseInfoOverride")
public class SchoolCourseInfoOverride {

    @XmlElement(name = "CourseCodeOverride")
    protected String courseCodeOverride;
    @XmlElement(name = "StateCourseCodeOverride")
    protected String stateCourseCodeOverride;
    @XmlElement(name = "DistrictCourseCodeOverride")
    protected String districtCourseCodeOverride;
    @XmlElement(name = "SubjectAreaOverride")
    protected SubjectAreaOverride subjectAreaOverride;
    @XmlElement(name = "CourseTitleOverride")
    protected String courseTitleOverride;
    @XmlElement(name = "InstructionalLevelOverride")
    protected String instructionalLevelOverride;
    @XmlElement(name = "CourseCreditsOverride", required = true)
    protected List<CourseCreditsOverride> courseCreditsOverride;
    @XmlAttribute(name = "Override", required = true)
    protected String override;

    /**
     * Gets the value of the courseCodeOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseCodeOverride() {
        return courseCodeOverride;
    }

    /**
     * Sets the value of the courseCodeOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseCodeOverride(String value) {
        this.courseCodeOverride = value;
    }

    /**
     * Gets the value of the stateCourseCodeOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCourseCodeOverride() {
        return stateCourseCodeOverride;
    }

    /**
     * Sets the value of the stateCourseCodeOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCourseCodeOverride(String value) {
        this.stateCourseCodeOverride = value;
    }

    /**
     * Gets the value of the districtCourseCodeOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictCourseCodeOverride() {
        return districtCourseCodeOverride;
    }

    /**
     * Sets the value of the districtCourseCodeOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictCourseCodeOverride(String value) {
        this.districtCourseCodeOverride = value;
    }

    /**
     * Gets the value of the subjectAreaOverride property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectAreaOverride }
     *     
     */
    public SubjectAreaOverride getSubjectAreaOverride() {
        return subjectAreaOverride;
    }

    /**
     * Sets the value of the subjectAreaOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectAreaOverride }
     *     
     */
    public void setSubjectAreaOverride(SubjectAreaOverride value) {
        this.subjectAreaOverride = value;
    }

    /**
     * Gets the value of the courseTitleOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseTitleOverride() {
        return courseTitleOverride;
    }

    /**
     * Sets the value of the courseTitleOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseTitleOverride(String value) {
        this.courseTitleOverride = value;
    }

    /**
     * Gets the value of the instructionalLevelOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructionalLevelOverride() {
        return instructionalLevelOverride;
    }

    /**
     * Sets the value of the instructionalLevelOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructionalLevelOverride(String value) {
        this.instructionalLevelOverride = value;
    }

    /**
     * Gets the value of the courseCreditsOverride property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the courseCreditsOverride property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourseCreditsOverride().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CourseCreditsOverride }
     * 
     * 
     */
    public List<CourseCreditsOverride> getCourseCreditsOverride() {
        if (courseCreditsOverride == null) {
            courseCreditsOverride = new ArrayList<CourseCreditsOverride>();
        }
        return this.courseCreditsOverride;
    }

    /**
     * Gets the value of the override property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverride() {
        return override;
    }

    /**
     * Sets the value of the override property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverride(String value) {
        this.override = value;
    }

}
