//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}LocalId" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StatePrId" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}NCESId" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolName" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolDistrict" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}OtherLEA" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolJurisdiction" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolType" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolFocus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolURL" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}PrincipalInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolContact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}PhoneNumber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}IdentificationInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SessionType" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}LowGradeLevel" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}HighGradeLevel" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}GradeLevels" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Title1Status" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}OperationalStatus" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CongressionalDistrict" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_ExtendedElements" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RefId" use="required" type="{http://www.sifinfo.org/infrastructure/1.x}RefIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localId",
    "statePrId",
    "ncesId",
    "schoolName",
    "schoolDistrict",
    "otherLEA",
    "schoolJurisdiction",
    "schoolType",
    "schoolFocus",
    "schoolURL",
    "principalInfo",
    "schoolContact",
    "phoneNumber",
    "address",
    "identificationInfo",
    "sessionType",
    "lowGradeLevel",
    "highGradeLevel",
    "gradeLevels",
    "title1Status",
    "operationalStatus",
    "congressionalDistrict",
    "sifExtendedElements"
})
@XmlRootElement(name = "SchoolInfo")
public class SchoolInfo {

    @XmlElement(name = "LocalId")
    protected String localId;
    @XmlElement(name = "StatePrId")
    protected String statePrId;
    @XmlElement(name = "NCESId")
    protected String ncesId;
    @XmlElement(name = "SchoolName")
    protected String schoolName;
    @XmlElement(name = "SchoolDistrict")
    protected SchoolDistrict schoolDistrict;
    @XmlElement(name = "OtherLEA", required = true)
    protected List<OtherLEA> otherLEA;
    @XmlElement(name = "SchoolJurisdiction")
    protected SchoolJurisdiction schoolJurisdiction;
    @XmlElement(name = "SchoolType")
    protected SchoolType schoolType;
    @XmlElement(name = "SchoolFocus", required = true)
    protected List<SchoolFocus> schoolFocus;
    @XmlElement(name = "SchoolURL")
    protected String schoolURL;
    @XmlElement(name = "PrincipalInfo")
    protected PrincipalInfo principalInfo;
    @XmlElement(name = "SchoolContact", required = true)
    protected List<SchoolContact> schoolContact;
    @XmlElement(name = "PhoneNumber", required = true)
    protected List<PhoneNumber> phoneNumber;
    @XmlElement(name = "Address", required = true)
    protected List<Address> address;
    @XmlElement(name = "IdentificationInfo", required = true)
    protected List<IdentificationInfo> identificationInfo;
    @XmlElement(name = "SessionType")
    protected SessionType sessionType;
    @XmlElement(name = "LowGradeLevel")
    protected String lowGradeLevel;
    @XmlElement(name = "HighGradeLevel")
    protected String highGradeLevel;
    @XmlElement(name = "GradeLevels")
    protected GradeLevels gradeLevels;
    @XmlElement(name = "Title1Status")
    protected String title1Status;
    @XmlElement(name = "OperationalStatus")
    protected String operationalStatus;
    @XmlElement(name = "CongressionalDistrict")
    protected String congressionalDistrict;
    @XmlElement(name = "SIF_ExtendedElements")
    protected SIFExtendedElements sifExtendedElements;
    @XmlAttribute(name = "RefId", required = true)
    protected String refId;

    /**
     * Gets the value of the localId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalId() {
        return localId;
    }

    /**
     * Sets the value of the localId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalId(String value) {
        this.localId = value;
    }

    /**
     * Gets the value of the statePrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatePrId() {
        return statePrId;
    }

    /**
     * Sets the value of the statePrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatePrId(String value) {
        this.statePrId = value;
    }

    /**
     * Gets the value of the ncesId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCESId() {
        return ncesId;
    }

    /**
     * Sets the value of the ncesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCESId(String value) {
        this.ncesId = value;
    }

    /**
     * Gets the value of the schoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * Sets the value of the schoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolName(String value) {
        this.schoolName = value;
    }

    /**
     * Gets the value of the schoolDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolDistrict }
     *     
     */
    public SchoolDistrict getSchoolDistrict() {
        return schoolDistrict;
    }

    /**
     * Sets the value of the schoolDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolDistrict }
     *     
     */
    public void setSchoolDistrict(SchoolDistrict value) {
        this.schoolDistrict = value;
    }

    /**
     * Gets the value of the otherLEA property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherLEA property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherLEA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherLEA }
     * 
     * 
     */
    public List<OtherLEA> getOtherLEA() {
        if (otherLEA == null) {
            otherLEA = new ArrayList<OtherLEA>();
        }
        return this.otherLEA;
    }

    /**
     * Gets the value of the schoolJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolJurisdiction }
     *     
     */
    public SchoolJurisdiction getSchoolJurisdiction() {
        return schoolJurisdiction;
    }

    /**
     * Sets the value of the schoolJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolJurisdiction }
     *     
     */
    public void setSchoolJurisdiction(SchoolJurisdiction value) {
        this.schoolJurisdiction = value;
    }

    /**
     * Gets the value of the schoolType property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolType }
     *     
     */
    public SchoolType getSchoolType() {
        return schoolType;
    }

    /**
     * Sets the value of the schoolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolType }
     *     
     */
    public void setSchoolType(SchoolType value) {
        this.schoolType = value;
    }

    /**
     * Gets the value of the schoolFocus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schoolFocus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchoolFocus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchoolFocus }
     * 
     * 
     */
    public List<SchoolFocus> getSchoolFocus() {
        if (schoolFocus == null) {
            schoolFocus = new ArrayList<SchoolFocus>();
        }
        return this.schoolFocus;
    }

    /**
     * Gets the value of the schoolURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolURL() {
        return schoolURL;
    }

    /**
     * Sets the value of the schoolURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolURL(String value) {
        this.schoolURL = value;
    }

    /**
     * Gets the value of the principalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PrincipalInfo }
     *     
     */
    public PrincipalInfo getPrincipalInfo() {
        return principalInfo;
    }

    /**
     * Sets the value of the principalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrincipalInfo }
     *     
     */
    public void setPrincipalInfo(PrincipalInfo value) {
        this.principalInfo = value;
    }

    /**
     * Gets the value of the schoolContact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schoolContact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchoolContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchoolContact }
     * 
     * 
     */
    public List<SchoolContact> getSchoolContact() {
        if (schoolContact == null) {
            schoolContact = new ArrayList<SchoolContact>();
        }
        return this.schoolContact;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhoneNumber }
     * 
     * 
     */
    public List<PhoneNumber> getPhoneNumber() {
        if (phoneNumber == null) {
            phoneNumber = new ArrayList<PhoneNumber>();
        }
        return this.phoneNumber;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the identificationInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationInfo }
     * 
     * 
     */
    public List<IdentificationInfo> getIdentificationInfo() {
        if (identificationInfo == null) {
            identificationInfo = new ArrayList<IdentificationInfo>();
        }
        return this.identificationInfo;
    }

    /**
     * Gets the value of the sessionType property.
     * 
     * @return
     *     possible object is
     *     {@link SessionType }
     *     
     */
    public SessionType getSessionType() {
        return sessionType;
    }

    /**
     * Sets the value of the sessionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionType }
     *     
     */
    public void setSessionType(SessionType value) {
        this.sessionType = value;
    }

    /**
     * Gets the value of the lowGradeLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowGradeLevel() {
        return lowGradeLevel;
    }

    /**
     * Sets the value of the lowGradeLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowGradeLevel(String value) {
        this.lowGradeLevel = value;
    }

    /**
     * Gets the value of the highGradeLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighGradeLevel() {
        return highGradeLevel;
    }

    /**
     * Sets the value of the highGradeLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighGradeLevel(String value) {
        this.highGradeLevel = value;
    }

    /**
     * Gets the value of the gradeLevels property.
     * 
     * @return
     *     possible object is
     *     {@link GradeLevels }
     *     
     */
    public GradeLevels getGradeLevels() {
        return gradeLevels;
    }

    /**
     * Sets the value of the gradeLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link GradeLevels }
     *     
     */
    public void setGradeLevels(GradeLevels value) {
        this.gradeLevels = value;
    }

    /**
     * Gets the value of the title1Status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle1Status() {
        return title1Status;
    }

    /**
     * Sets the value of the title1Status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle1Status(String value) {
        this.title1Status = value;
    }

    /**
     * Gets the value of the operationalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalStatus() {
        return operationalStatus;
    }

    /**
     * Sets the value of the operationalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalStatus(String value) {
        this.operationalStatus = value;
    }

    /**
     * Gets the value of the congressionalDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCongressionalDistrict() {
        return congressionalDistrict;
    }

    /**
     * Sets the value of the congressionalDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCongressionalDistrict(String value) {
        this.congressionalDistrict = value;
    }

    /**
     * Gets the value of the sifExtendedElements property.
     * 
     * @return
     *     possible object is
     *     {@link SIFExtendedElements }
     *     
     */
    public SIFExtendedElements getSIFExtendedElements() {
        return sifExtendedElements;
    }

    /**
     * Sets the value of the sifExtendedElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFExtendedElements }
     *     
     */
    public void setSIFExtendedElements(SIFExtendedElements value) {
        this.sifExtendedElements = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

}
