//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Diagnostic" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}ScoreValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Min" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Max" minOccurs="0"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Cut" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RefIdType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="SIF_GUID"/>
 *             &lt;enumeration value="URI"/>
 *             &lt;enumeration value="Namestring"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ScoreRefId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diagnostic",
    "scoreValue",
    "min",
    "max",
    "cut"
})
@XmlRootElement(name = "Score")
public class Score {

    @XmlElement(name = "Diagnostic", required = true)
    protected List<Diagnostic> diagnostic;
    @XmlElement(name = "ScoreValue", required = true)
    protected List<ScoreValue> scoreValue;
    @XmlElement(name = "Min")
    protected String min;
    @XmlElement(name = "Max")
    protected String max;
    @XmlElement(name = "Cut")
    protected String cut;
    @XmlAttribute(name = "RefIdType", required = true)
    protected String refIdType;
    @XmlAttribute(name = "ScoreRefId", required = true)
    protected String scoreRefId;

    /**
     * Gets the value of the diagnostic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnostic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnostic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Diagnostic }
     * 
     * 
     */
    public List<Diagnostic> getDiagnostic() {
        if (diagnostic == null) {
            diagnostic = new ArrayList<Diagnostic>();
        }
        return this.diagnostic;
    }

    /**
     * Gets the value of the scoreValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scoreValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScoreValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreValue }
     * 
     * 
     */
    public List<ScoreValue> getScoreValue() {
        if (scoreValue == null) {
            scoreValue = new ArrayList<ScoreValue>();
        }
        return this.scoreValue;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMin(String value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMax(String value) {
        this.max = value;
    }

    /**
     * Gets the value of the cut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCut() {
        return cut;
    }

    /**
     * Sets the value of the cut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCut(String value) {
        this.cut = value;
    }

    /**
     * Gets the value of the refIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefIdType() {
        return refIdType;
    }

    /**
     * Sets the value of the refIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefIdType(String value) {
        this.refIdType = value;
    }

    /**
     * Gets the value of the scoreRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreRefId() {
        return scoreRefId;
    }

    /**
     * Sets the value of the scoreRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreRefId(String value) {
        this.scoreRefId = value;
    }

}
