//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sifinfo.org/infrastructure/1.x}SIF_MessageType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_OriginalSourceId"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_OriginalMsgId"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Status"/>
 *           &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Error"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sifOriginalSourceId",
    "sifOriginalMsgId",
    "sifStatus",
    "sifError"
})
@XmlRootElement(name = "SIF_Ack")
public class SIFAck
    extends SIFMessageType
{

    @XmlElement(name = "SIF_OriginalSourceId", required = true)
    protected String sifOriginalSourceId;
    @XmlElement(name = "SIF_OriginalMsgId", required = true)
    protected String sifOriginalMsgId;
    @XmlElement(name = "SIF_Status")
    protected SIFStatus sifStatus;
    @XmlElement(name = "SIF_Error")
    protected SIFError sifError;

    /**
     * Gets the value of the sifOriginalSourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIFOriginalSourceId() {
        return sifOriginalSourceId;
    }

    /**
     * Sets the value of the sifOriginalSourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIFOriginalSourceId(String value) {
        this.sifOriginalSourceId = value;
    }

    /**
     * Gets the value of the sifOriginalMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIFOriginalMsgId() {
        return sifOriginalMsgId;
    }

    /**
     * Sets the value of the sifOriginalMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIFOriginalMsgId(String value) {
        this.sifOriginalMsgId = value;
    }

    /**
     * Gets the value of the sifStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SIFStatus }
     *     
     */
    public SIFStatus getSIFStatus() {
        return sifStatus;
    }

    /**
     * Sets the value of the sifStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFStatus }
     *     
     */
    public void setSIFStatus(SIFStatus value) {
        this.sifStatus = value;
    }

    /**
     * Gets the value of the sifError property.
     * 
     * @return
     *     possible object is
     *     {@link SIFError }
     *     
     */
    public SIFError getSIFError() {
        return sifError;
    }

    /**
     * Sets the value of the sifError property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFError }
     *     
     */
    public void setSIFError(SIFError value) {
        this.sifError = value;
    }

}
