//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AggregateStatisticInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AggregateCharacteristicInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AggregateStatisticFact"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentMeal"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceItem"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceItemUnit"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceItemPortion"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceReimbursementRates"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceMealPrices"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StaffMeal"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceTransaction"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceTransactionDetails"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceTransactionPayMethod"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceSales"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FoodserviceItemSales"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AccountingPeriod"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FinancialAccount"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FinancialAccountAccountingPeriodLocationInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FinancialClass"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FinancialIncomeStatement"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FinancialTransaction"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}FiscalYear"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Billing"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Payment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}ActivityProvider"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EmployeeAssignment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EmployeeContract"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EmployeeCredit"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EmployeeHR"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EmployeePersonal"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EmployeePicture"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}ProfDevActivities"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StaffAssignment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}TimeWorked"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}VendorInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}W4"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}EmployeeWage"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}LocationInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Purchasing"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}LearningStandardDocument"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}LearningStandardItem"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}CurriculumStructure"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Lesson"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Activity"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Assignment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Assessment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AssessmentSection"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AssessmentItem"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AssessmentSubTest"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentResultSet"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}LearningResource"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentParticipation"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentPlacement"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}AttendanceCodeInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}RoomInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}RoomType"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolCourseInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SchoolInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SectionInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StaffPersonal"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentContact"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentDailyAttendance"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentPersonal"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentPicture"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentSchoolEnrollment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentSectionEnrollment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}TermInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}LEAInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BusEquipment"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BusInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BusRouteDetail"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BusRouteInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BusStopInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}StudentTransportInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}BusPositionInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}ReportManifest"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}ReportAuthorityInfo"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_ReportObject"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_LogEntry"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}Authentication"/>
 *       &lt;/choice>
 *       &lt;attribute name="Action" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Add"/>
 *             &lt;enumeration value="Delete"/>
 *             &lt;enumeration value="Change"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ObjectName" use="required" type="{http://www.sifinfo.org/infrastructure/1.x}SubscribeObjectNames" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aggregateStatisticInfo",
    "aggregateCharacteristicInfo",
    "aggregateStatisticFact",
    "studentMeal",
    "foodserviceItem",
    "foodserviceItemUnit",
    "foodserviceItemPortion",
    "foodserviceReimbursementRates",
    "foodserviceMealPrices",
    "staffMeal",
    "foodserviceTransaction",
    "foodserviceTransactionDetails",
    "foodserviceTransactionPayMethod",
    "foodserviceSales",
    "foodserviceItemSales",
    "accountingPeriod",
    "financialAccount",
    "financialAccountAccountingPeriodLocationInfo",
    "financialClass",
    "financialIncomeStatement",
    "financialTransaction",
    "fiscalYear",
    "billing",
    "payment",
    "activityProvider",
    "employeeAssignment",
    "employeeContract",
    "employeeCredit",
    "employeeHR",
    "employeePersonal",
    "employeePicture",
    "profDevActivities",
    "staffAssignment",
    "timeWorked",
    "vendorInfo",
    "w4",
    "employeeWage",
    "locationInfo",
    "purchasing",
    "learningStandardDocument",
    "learningStandardItem",
    "curriculumStructure",
    "lesson",
    "activity",
    "assignment",
    "assessment",
    "assessmentSection",
    "assessmentItem",
    "assessmentSubTest",
    "studentResultSet",
    "learningResource",
    "studentParticipation",
    "studentPlacement",
    "attendanceCodeInfo",
    "roomInfo",
    "roomType",
    "schoolCourseInfo",
    "schoolInfo",
    "sectionInfo",
    "staffPersonal",
    "studentContact",
    "studentDailyAttendance",
    "studentPersonal",
    "studentPicture",
    "studentSchoolEnrollment",
    "studentSectionEnrollment",
    "termInfo",
    "leaInfo",
    "busEquipment",
    "busInfo",
    "busRouteDetail",
    "busRouteInfo",
    "busStopInfo",
    "studentTransportInfo",
    "busPositionInfo",
    "reportManifest",
    "reportAuthorityInfo",
    "sifReportObject",
    "sifLogEntry",
    "authentication"
})
@XmlRootElement(name = "SIF_EventObject")
public class SIFEventObject {

    @XmlElement(name = "AggregateStatisticInfo")
    protected AggregateStatisticInfo aggregateStatisticInfo;
    @XmlElement(name = "AggregateCharacteristicInfo")
    protected AggregateCharacteristicInfo aggregateCharacteristicInfo;
    @XmlElement(name = "AggregateStatisticFact")
    protected AggregateStatisticFact aggregateStatisticFact;
    @XmlElement(name = "StudentMeal")
    protected StudentMeal studentMeal;
    @XmlElement(name = "FoodserviceItem")
    protected FoodserviceItem foodserviceItem;
    @XmlElement(name = "FoodserviceItemUnit")
    protected FoodserviceItemUnit foodserviceItemUnit;
    @XmlElement(name = "FoodserviceItemPortion")
    protected FoodserviceItemPortion foodserviceItemPortion;
    @XmlElement(name = "FoodserviceReimbursementRates")
    protected FoodserviceReimbursementRates foodserviceReimbursementRates;
    @XmlElement(name = "FoodserviceMealPrices")
    protected FoodserviceMealPrices foodserviceMealPrices;
    @XmlElement(name = "StaffMeal")
    protected StaffMeal staffMeal;
    @XmlElement(name = "FoodserviceTransaction")
    protected FoodserviceTransaction foodserviceTransaction;
    @XmlElement(name = "FoodserviceTransactionDetails")
    protected FoodserviceTransactionDetails foodserviceTransactionDetails;
    @XmlElement(name = "FoodserviceTransactionPayMethod")
    protected FoodserviceTransactionPayMethod foodserviceTransactionPayMethod;
    @XmlElement(name = "FoodserviceSales")
    protected FoodserviceSales foodserviceSales;
    @XmlElement(name = "FoodserviceItemSales")
    protected FoodserviceItemSales foodserviceItemSales;
    @XmlElement(name = "AccountingPeriod")
    protected AccountingPeriod accountingPeriod;
    @XmlElement(name = "FinancialAccount")
    protected FinancialAccount financialAccount;
    @XmlElement(name = "FinancialAccountAccountingPeriodLocationInfo")
    protected FinancialAccountAccountingPeriodLocationInfo financialAccountAccountingPeriodLocationInfo;
    @XmlElement(name = "FinancialClass")
    protected FinancialClass financialClass;
    @XmlElement(name = "FinancialIncomeStatement")
    protected FinancialIncomeStatement financialIncomeStatement;
    @XmlElement(name = "FinancialTransaction")
    protected FinancialTransaction financialTransaction;
    @XmlElement(name = "FiscalYear")
    protected FiscalYear fiscalYear;
    @XmlElement(name = "Billing")
    protected Billing billing;
    @XmlElement(name = "Payment")
    protected Payment payment;
    @XmlElement(name = "ActivityProvider")
    protected ActivityProvider activityProvider;
    @XmlElement(name = "EmployeeAssignment")
    protected EmployeeAssignment employeeAssignment;
    @XmlElement(name = "EmployeeContract")
    protected EmployeeContract employeeContract;
    @XmlElement(name = "EmployeeCredit")
    protected EmployeeCredit employeeCredit;
    @XmlElement(name = "EmployeeHR")
    protected EmployeeHR employeeHR;
    @XmlElement(name = "EmployeePersonal")
    protected EmployeePersonal employeePersonal;
    @XmlElement(name = "EmployeePicture")
    protected EmployeePicture employeePicture;
    @XmlElement(name = "ProfDevActivities")
    protected ProfDevActivities profDevActivities;
    @XmlElement(name = "StaffAssignment")
    protected StaffAssignment staffAssignment;
    @XmlElement(name = "TimeWorked")
    protected TimeWorked timeWorked;
    @XmlElement(name = "VendorInfo")
    protected VendorInfo vendorInfo;
    @XmlElement(name = "W4")
    protected W4 w4;
    @XmlElement(name = "EmployeeWage")
    protected EmployeeWage employeeWage;
    @XmlElement(name = "LocationInfo")
    protected LocationInfo locationInfo;
    @XmlElement(name = "Purchasing")
    protected Purchasing purchasing;
    @XmlElement(name = "LearningStandardDocument")
    protected LearningStandardDocument learningStandardDocument;
    @XmlElement(name = "LearningStandardItem")
    protected LearningStandardItem learningStandardItem;
    @XmlElement(name = "CurriculumStructure")
    protected CurriculumStructure curriculumStructure;
    @XmlElement(name = "Lesson")
    protected Lesson lesson;
    @XmlElement(name = "Activity")
    protected Activity activity;
    @XmlElement(name = "Assignment")
    protected Assignment assignment;
    @XmlElement(name = "Assessment")
    protected Assessment assessment;
    @XmlElement(name = "AssessmentSection")
    protected AssessmentSection assessmentSection;
    @XmlElement(name = "AssessmentItem")
    protected AssessmentItem assessmentItem;
    @XmlElement(name = "AssessmentSubTest")
    protected AssessmentSubTest assessmentSubTest;
    @XmlElement(name = "StudentResultSet")
    protected StudentResultSet studentResultSet;
    @XmlElement(name = "LearningResource")
    protected LearningResource learningResource;
    @XmlElement(name = "StudentParticipation")
    protected StudentParticipation studentParticipation;
    @XmlElement(name = "StudentPlacement")
    protected StudentPlacement studentPlacement;
    @XmlElement(name = "AttendanceCodeInfo")
    protected AttendanceCodeInfo attendanceCodeInfo;
    @XmlElement(name = "RoomInfo")
    protected RoomInfo roomInfo;
    @XmlElement(name = "RoomType")
    protected RoomType roomType;
    @XmlElement(name = "SchoolCourseInfo")
    protected SchoolCourseInfo schoolCourseInfo;
    @XmlElement(name = "SchoolInfo")
    protected SchoolInfo schoolInfo;
    @XmlElement(name = "SectionInfo")
    protected SectionInfo sectionInfo;
    @XmlElement(name = "StaffPersonal")
    protected StaffPersonal staffPersonal;
    @XmlElement(name = "StudentContact")
    protected StudentContact studentContact;
    @XmlElement(name = "StudentDailyAttendance")
    protected StudentDailyAttendance studentDailyAttendance;
    @XmlElement(name = "StudentPersonal")
    protected StudentPersonal studentPersonal;
    @XmlElement(name = "StudentPicture")
    protected StudentPicture studentPicture;
    @XmlElement(name = "StudentSchoolEnrollment")
    protected StudentSchoolEnrollment studentSchoolEnrollment;
    @XmlElement(name = "StudentSectionEnrollment")
    protected StudentSectionEnrollment studentSectionEnrollment;
    @XmlElement(name = "TermInfo")
    protected TermInfo termInfo;
    @XmlElement(name = "LEAInfo")
    protected LEAInfo leaInfo;
    @XmlElement(name = "BusEquipment")
    protected BusEquipment busEquipment;
    @XmlElement(name = "BusInfo")
    protected BusInfo busInfo;
    @XmlElement(name = "BusRouteDetail")
    protected BusRouteDetail busRouteDetail;
    @XmlElement(name = "BusRouteInfo")
    protected BusRouteInfo busRouteInfo;
    @XmlElement(name = "BusStopInfo")
    protected BusStopInfo busStopInfo;
    @XmlElement(name = "StudentTransportInfo")
    protected StudentTransportInfo studentTransportInfo;
    @XmlElement(name = "BusPositionInfo")
    protected BusPositionInfo busPositionInfo;
    @XmlElement(name = "ReportManifest")
    protected ReportManifest reportManifest;
    @XmlElement(name = "ReportAuthorityInfo")
    protected ReportAuthorityInfo reportAuthorityInfo;
    @XmlElement(name = "SIF_ReportObject")
    protected SIFReportObject sifReportObject;
    @XmlElement(name = "SIF_LogEntry")
    protected SIFLogEntry sifLogEntry;
    @XmlElement(name = "Authentication")
    protected Authentication authentication;
    @XmlAttribute(name = "Action", required = true)
    protected String action;
    @XmlAttribute(name = "ObjectName", required = true)
    protected SubscribeObjectNames objectName;

    /**
     * Gets the value of the aggregateStatisticInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AggregateStatisticInfo }
     *     
     */
    public AggregateStatisticInfo getAggregateStatisticInfo() {
        return aggregateStatisticInfo;
    }

    /**
     * Sets the value of the aggregateStatisticInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregateStatisticInfo }
     *     
     */
    public void setAggregateStatisticInfo(AggregateStatisticInfo value) {
        this.aggregateStatisticInfo = value;
    }

    /**
     * Gets the value of the aggregateCharacteristicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AggregateCharacteristicInfo }
     *     
     */
    public AggregateCharacteristicInfo getAggregateCharacteristicInfo() {
        return aggregateCharacteristicInfo;
    }

    /**
     * Sets the value of the aggregateCharacteristicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregateCharacteristicInfo }
     *     
     */
    public void setAggregateCharacteristicInfo(AggregateCharacteristicInfo value) {
        this.aggregateCharacteristicInfo = value;
    }

    /**
     * Gets the value of the aggregateStatisticFact property.
     * 
     * @return
     *     possible object is
     *     {@link AggregateStatisticFact }
     *     
     */
    public AggregateStatisticFact getAggregateStatisticFact() {
        return aggregateStatisticFact;
    }

    /**
     * Sets the value of the aggregateStatisticFact property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregateStatisticFact }
     *     
     */
    public void setAggregateStatisticFact(AggregateStatisticFact value) {
        this.aggregateStatisticFact = value;
    }

    /**
     * Gets the value of the studentMeal property.
     * 
     * @return
     *     possible object is
     *     {@link StudentMeal }
     *     
     */
    public StudentMeal getStudentMeal() {
        return studentMeal;
    }

    /**
     * Sets the value of the studentMeal property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentMeal }
     *     
     */
    public void setStudentMeal(StudentMeal value) {
        this.studentMeal = value;
    }

    /**
     * Gets the value of the foodserviceItem property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceItem }
     *     
     */
    public FoodserviceItem getFoodserviceItem() {
        return foodserviceItem;
    }

    /**
     * Sets the value of the foodserviceItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceItem }
     *     
     */
    public void setFoodserviceItem(FoodserviceItem value) {
        this.foodserviceItem = value;
    }

    /**
     * Gets the value of the foodserviceItemUnit property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceItemUnit }
     *     
     */
    public FoodserviceItemUnit getFoodserviceItemUnit() {
        return foodserviceItemUnit;
    }

    /**
     * Sets the value of the foodserviceItemUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceItemUnit }
     *     
     */
    public void setFoodserviceItemUnit(FoodserviceItemUnit value) {
        this.foodserviceItemUnit = value;
    }

    /**
     * Gets the value of the foodserviceItemPortion property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceItemPortion }
     *     
     */
    public FoodserviceItemPortion getFoodserviceItemPortion() {
        return foodserviceItemPortion;
    }

    /**
     * Sets the value of the foodserviceItemPortion property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceItemPortion }
     *     
     */
    public void setFoodserviceItemPortion(FoodserviceItemPortion value) {
        this.foodserviceItemPortion = value;
    }

    /**
     * Gets the value of the foodserviceReimbursementRates property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceReimbursementRates }
     *     
     */
    public FoodserviceReimbursementRates getFoodserviceReimbursementRates() {
        return foodserviceReimbursementRates;
    }

    /**
     * Sets the value of the foodserviceReimbursementRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceReimbursementRates }
     *     
     */
    public void setFoodserviceReimbursementRates(FoodserviceReimbursementRates value) {
        this.foodserviceReimbursementRates = value;
    }

    /**
     * Gets the value of the foodserviceMealPrices property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceMealPrices }
     *     
     */
    public FoodserviceMealPrices getFoodserviceMealPrices() {
        return foodserviceMealPrices;
    }

    /**
     * Sets the value of the foodserviceMealPrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceMealPrices }
     *     
     */
    public void setFoodserviceMealPrices(FoodserviceMealPrices value) {
        this.foodserviceMealPrices = value;
    }

    /**
     * Gets the value of the staffMeal property.
     * 
     * @return
     *     possible object is
     *     {@link StaffMeal }
     *     
     */
    public StaffMeal getStaffMeal() {
        return staffMeal;
    }

    /**
     * Sets the value of the staffMeal property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffMeal }
     *     
     */
    public void setStaffMeal(StaffMeal value) {
        this.staffMeal = value;
    }

    /**
     * Gets the value of the foodserviceTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceTransaction }
     *     
     */
    public FoodserviceTransaction getFoodserviceTransaction() {
        return foodserviceTransaction;
    }

    /**
     * Sets the value of the foodserviceTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceTransaction }
     *     
     */
    public void setFoodserviceTransaction(FoodserviceTransaction value) {
        this.foodserviceTransaction = value;
    }

    /**
     * Gets the value of the foodserviceTransactionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceTransactionDetails }
     *     
     */
    public FoodserviceTransactionDetails getFoodserviceTransactionDetails() {
        return foodserviceTransactionDetails;
    }

    /**
     * Sets the value of the foodserviceTransactionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceTransactionDetails }
     *     
     */
    public void setFoodserviceTransactionDetails(FoodserviceTransactionDetails value) {
        this.foodserviceTransactionDetails = value;
    }

    /**
     * Gets the value of the foodserviceTransactionPayMethod property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceTransactionPayMethod }
     *     
     */
    public FoodserviceTransactionPayMethod getFoodserviceTransactionPayMethod() {
        return foodserviceTransactionPayMethod;
    }

    /**
     * Sets the value of the foodserviceTransactionPayMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceTransactionPayMethod }
     *     
     */
    public void setFoodserviceTransactionPayMethod(FoodserviceTransactionPayMethod value) {
        this.foodserviceTransactionPayMethod = value;
    }

    /**
     * Gets the value of the foodserviceSales property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceSales }
     *     
     */
    public FoodserviceSales getFoodserviceSales() {
        return foodserviceSales;
    }

    /**
     * Sets the value of the foodserviceSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceSales }
     *     
     */
    public void setFoodserviceSales(FoodserviceSales value) {
        this.foodserviceSales = value;
    }

    /**
     * Gets the value of the foodserviceItemSales property.
     * 
     * @return
     *     possible object is
     *     {@link FoodserviceItemSales }
     *     
     */
    public FoodserviceItemSales getFoodserviceItemSales() {
        return foodserviceItemSales;
    }

    /**
     * Sets the value of the foodserviceItemSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoodserviceItemSales }
     *     
     */
    public void setFoodserviceItemSales(FoodserviceItemSales value) {
        this.foodserviceItemSales = value;
    }

    /**
     * Gets the value of the accountingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingPeriod }
     *     
     */
    public AccountingPeriod getAccountingPeriod() {
        return accountingPeriod;
    }

    /**
     * Sets the value of the accountingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingPeriod }
     *     
     */
    public void setAccountingPeriod(AccountingPeriod value) {
        this.accountingPeriod = value;
    }

    /**
     * Gets the value of the financialAccount property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialAccount }
     *     
     */
    public FinancialAccount getFinancialAccount() {
        return financialAccount;
    }

    /**
     * Sets the value of the financialAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialAccount }
     *     
     */
    public void setFinancialAccount(FinancialAccount value) {
        this.financialAccount = value;
    }

    /**
     * Gets the value of the financialAccountAccountingPeriodLocationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialAccountAccountingPeriodLocationInfo }
     *     
     */
    public FinancialAccountAccountingPeriodLocationInfo getFinancialAccountAccountingPeriodLocationInfo() {
        return financialAccountAccountingPeriodLocationInfo;
    }

    /**
     * Sets the value of the financialAccountAccountingPeriodLocationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialAccountAccountingPeriodLocationInfo }
     *     
     */
    public void setFinancialAccountAccountingPeriodLocationInfo(FinancialAccountAccountingPeriodLocationInfo value) {
        this.financialAccountAccountingPeriodLocationInfo = value;
    }

    /**
     * Gets the value of the financialClass property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialClass }
     *     
     */
    public FinancialClass getFinancialClass() {
        return financialClass;
    }

    /**
     * Sets the value of the financialClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialClass }
     *     
     */
    public void setFinancialClass(FinancialClass value) {
        this.financialClass = value;
    }

    /**
     * Gets the value of the financialIncomeStatement property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialIncomeStatement }
     *     
     */
    public FinancialIncomeStatement getFinancialIncomeStatement() {
        return financialIncomeStatement;
    }

    /**
     * Sets the value of the financialIncomeStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialIncomeStatement }
     *     
     */
    public void setFinancialIncomeStatement(FinancialIncomeStatement value) {
        this.financialIncomeStatement = value;
    }

    /**
     * Gets the value of the financialTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialTransaction }
     *     
     */
    public FinancialTransaction getFinancialTransaction() {
        return financialTransaction;
    }

    /**
     * Sets the value of the financialTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialTransaction }
     *     
     */
    public void setFinancialTransaction(FinancialTransaction value) {
        this.financialTransaction = value;
    }

    /**
     * Gets the value of the fiscalYear property.
     * 
     * @return
     *     possible object is
     *     {@link FiscalYear }
     *     
     */
    public FiscalYear getFiscalYear() {
        return fiscalYear;
    }

    /**
     * Sets the value of the fiscalYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiscalYear }
     *     
     */
    public void setFiscalYear(FiscalYear value) {
        this.fiscalYear = value;
    }

    /**
     * Gets the value of the billing property.
     * 
     * @return
     *     possible object is
     *     {@link Billing }
     *     
     */
    public Billing getBilling() {
        return billing;
    }

    /**
     * Sets the value of the billing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Billing }
     *     
     */
    public void setBilling(Billing value) {
        this.billing = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the activityProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityProvider }
     *     
     */
    public ActivityProvider getActivityProvider() {
        return activityProvider;
    }

    /**
     * Sets the value of the activityProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityProvider }
     *     
     */
    public void setActivityProvider(ActivityProvider value) {
        this.activityProvider = value;
    }

    /**
     * Gets the value of the employeeAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeAssignment }
     *     
     */
    public EmployeeAssignment getEmployeeAssignment() {
        return employeeAssignment;
    }

    /**
     * Sets the value of the employeeAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeAssignment }
     *     
     */
    public void setEmployeeAssignment(EmployeeAssignment value) {
        this.employeeAssignment = value;
    }

    /**
     * Gets the value of the employeeContract property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeContract }
     *     
     */
    public EmployeeContract getEmployeeContract() {
        return employeeContract;
    }

    /**
     * Sets the value of the employeeContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeContract }
     *     
     */
    public void setEmployeeContract(EmployeeContract value) {
        this.employeeContract = value;
    }

    /**
     * Gets the value of the employeeCredit property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeCredit }
     *     
     */
    public EmployeeCredit getEmployeeCredit() {
        return employeeCredit;
    }

    /**
     * Sets the value of the employeeCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeCredit }
     *     
     */
    public void setEmployeeCredit(EmployeeCredit value) {
        this.employeeCredit = value;
    }

    /**
     * Gets the value of the employeeHR property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeHR }
     *     
     */
    public EmployeeHR getEmployeeHR() {
        return employeeHR;
    }

    /**
     * Sets the value of the employeeHR property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeHR }
     *     
     */
    public void setEmployeeHR(EmployeeHR value) {
        this.employeeHR = value;
    }

    /**
     * Gets the value of the employeePersonal property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeePersonal }
     *     
     */
    public EmployeePersonal getEmployeePersonal() {
        return employeePersonal;
    }

    /**
     * Sets the value of the employeePersonal property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeePersonal }
     *     
     */
    public void setEmployeePersonal(EmployeePersonal value) {
        this.employeePersonal = value;
    }

    /**
     * Gets the value of the employeePicture property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeePicture }
     *     
     */
    public EmployeePicture getEmployeePicture() {
        return employeePicture;
    }

    /**
     * Sets the value of the employeePicture property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeePicture }
     *     
     */
    public void setEmployeePicture(EmployeePicture value) {
        this.employeePicture = value;
    }

    /**
     * Gets the value of the profDevActivities property.
     * 
     * @return
     *     possible object is
     *     {@link ProfDevActivities }
     *     
     */
    public ProfDevActivities getProfDevActivities() {
        return profDevActivities;
    }

    /**
     * Sets the value of the profDevActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfDevActivities }
     *     
     */
    public void setProfDevActivities(ProfDevActivities value) {
        this.profDevActivities = value;
    }

    /**
     * Gets the value of the staffAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link StaffAssignment }
     *     
     */
    public StaffAssignment getStaffAssignment() {
        return staffAssignment;
    }

    /**
     * Sets the value of the staffAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffAssignment }
     *     
     */
    public void setStaffAssignment(StaffAssignment value) {
        this.staffAssignment = value;
    }

    /**
     * Gets the value of the timeWorked property.
     * 
     * @return
     *     possible object is
     *     {@link TimeWorked }
     *     
     */
    public TimeWorked getTimeWorked() {
        return timeWorked;
    }

    /**
     * Sets the value of the timeWorked property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeWorked }
     *     
     */
    public void setTimeWorked(TimeWorked value) {
        this.timeWorked = value;
    }

    /**
     * Gets the value of the vendorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link VendorInfo }
     *     
     */
    public VendorInfo getVendorInfo() {
        return vendorInfo;
    }

    /**
     * Sets the value of the vendorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorInfo }
     *     
     */
    public void setVendorInfo(VendorInfo value) {
        this.vendorInfo = value;
    }

    /**
     * Gets the value of the w4 property.
     * 
     * @return
     *     possible object is
     *     {@link W4 }
     *     
     */
    public W4 getW4() {
        return w4;
    }

    /**
     * Sets the value of the w4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link W4 }
     *     
     */
    public void setW4(W4 value) {
        this.w4 = value;
    }

    /**
     * Gets the value of the employeeWage property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeWage }
     *     
     */
    public EmployeeWage getEmployeeWage() {
        return employeeWage;
    }

    /**
     * Sets the value of the employeeWage property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeWage }
     *     
     */
    public void setEmployeeWage(EmployeeWage value) {
        this.employeeWage = value;
    }

    /**
     * Gets the value of the locationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LocationInfo }
     *     
     */
    public LocationInfo getLocationInfo() {
        return locationInfo;
    }

    /**
     * Sets the value of the locationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationInfo }
     *     
     */
    public void setLocationInfo(LocationInfo value) {
        this.locationInfo = value;
    }

    /**
     * Gets the value of the purchasing property.
     * 
     * @return
     *     possible object is
     *     {@link Purchasing }
     *     
     */
    public Purchasing getPurchasing() {
        return purchasing;
    }

    /**
     * Sets the value of the purchasing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purchasing }
     *     
     */
    public void setPurchasing(Purchasing value) {
        this.purchasing = value;
    }

    /**
     * Gets the value of the learningStandardDocument property.
     * 
     * @return
     *     possible object is
     *     {@link LearningStandardDocument }
     *     
     */
    public LearningStandardDocument getLearningStandardDocument() {
        return learningStandardDocument;
    }

    /**
     * Sets the value of the learningStandardDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningStandardDocument }
     *     
     */
    public void setLearningStandardDocument(LearningStandardDocument value) {
        this.learningStandardDocument = value;
    }

    /**
     * Gets the value of the learningStandardItem property.
     * 
     * @return
     *     possible object is
     *     {@link LearningStandardItem }
     *     
     */
    public LearningStandardItem getLearningStandardItem() {
        return learningStandardItem;
    }

    /**
     * Sets the value of the learningStandardItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningStandardItem }
     *     
     */
    public void setLearningStandardItem(LearningStandardItem value) {
        this.learningStandardItem = value;
    }

    /**
     * Gets the value of the curriculumStructure property.
     * 
     * @return
     *     possible object is
     *     {@link CurriculumStructure }
     *     
     */
    public CurriculumStructure getCurriculumStructure() {
        return curriculumStructure;
    }

    /**
     * Sets the value of the curriculumStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurriculumStructure }
     *     
     */
    public void setCurriculumStructure(CurriculumStructure value) {
        this.curriculumStructure = value;
    }

    /**
     * Gets the value of the lesson property.
     * 
     * @return
     *     possible object is
     *     {@link Lesson }
     *     
     */
    public Lesson getLesson() {
        return lesson;
    }

    /**
     * Sets the value of the lesson property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lesson }
     *     
     */
    public void setLesson(Lesson value) {
        this.lesson = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link Activity }
     *     
     */
    public Activity getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Activity }
     *     
     */
    public void setActivity(Activity value) {
        this.activity = value;
    }

    /**
     * Gets the value of the assignment property.
     * 
     * @return
     *     possible object is
     *     {@link Assignment }
     *     
     */
    public Assignment getAssignment() {
        return assignment;
    }

    /**
     * Sets the value of the assignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assignment }
     *     
     */
    public void setAssignment(Assignment value) {
        this.assignment = value;
    }

    /**
     * Gets the value of the assessment property.
     * 
     * @return
     *     possible object is
     *     {@link Assessment }
     *     
     */
    public Assessment getAssessment() {
        return assessment;
    }

    /**
     * Sets the value of the assessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assessment }
     *     
     */
    public void setAssessment(Assessment value) {
        this.assessment = value;
    }

    /**
     * Gets the value of the assessmentSection property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentSection }
     *     
     */
    public AssessmentSection getAssessmentSection() {
        return assessmentSection;
    }

    /**
     * Sets the value of the assessmentSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentSection }
     *     
     */
    public void setAssessmentSection(AssessmentSection value) {
        this.assessmentSection = value;
    }

    /**
     * Gets the value of the assessmentItem property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentItem }
     *     
     */
    public AssessmentItem getAssessmentItem() {
        return assessmentItem;
    }

    /**
     * Sets the value of the assessmentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentItem }
     *     
     */
    public void setAssessmentItem(AssessmentItem value) {
        this.assessmentItem = value;
    }

    /**
     * Gets the value of the assessmentSubTest property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentSubTest }
     *     
     */
    public AssessmentSubTest getAssessmentSubTest() {
        return assessmentSubTest;
    }

    /**
     * Sets the value of the assessmentSubTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentSubTest }
     *     
     */
    public void setAssessmentSubTest(AssessmentSubTest value) {
        this.assessmentSubTest = value;
    }

    /**
     * Gets the value of the studentResultSet property.
     * 
     * @return
     *     possible object is
     *     {@link StudentResultSet }
     *     
     */
    public StudentResultSet getStudentResultSet() {
        return studentResultSet;
    }

    /**
     * Sets the value of the studentResultSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentResultSet }
     *     
     */
    public void setStudentResultSet(StudentResultSet value) {
        this.studentResultSet = value;
    }

    /**
     * Gets the value of the learningResource property.
     * 
     * @return
     *     possible object is
     *     {@link LearningResource }
     *     
     */
    public LearningResource getLearningResource() {
        return learningResource;
    }

    /**
     * Sets the value of the learningResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningResource }
     *     
     */
    public void setLearningResource(LearningResource value) {
        this.learningResource = value;
    }

    /**
     * Gets the value of the studentParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link StudentParticipation }
     *     
     */
    public StudentParticipation getStudentParticipation() {
        return studentParticipation;
    }

    /**
     * Sets the value of the studentParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentParticipation }
     *     
     */
    public void setStudentParticipation(StudentParticipation value) {
        this.studentParticipation = value;
    }

    /**
     * Gets the value of the studentPlacement property.
     * 
     * @return
     *     possible object is
     *     {@link StudentPlacement }
     *     
     */
    public StudentPlacement getStudentPlacement() {
        return studentPlacement;
    }

    /**
     * Sets the value of the studentPlacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentPlacement }
     *     
     */
    public void setStudentPlacement(StudentPlacement value) {
        this.studentPlacement = value;
    }

    /**
     * Gets the value of the attendanceCodeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AttendanceCodeInfo }
     *     
     */
    public AttendanceCodeInfo getAttendanceCodeInfo() {
        return attendanceCodeInfo;
    }

    /**
     * Sets the value of the attendanceCodeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttendanceCodeInfo }
     *     
     */
    public void setAttendanceCodeInfo(AttendanceCodeInfo value) {
        this.attendanceCodeInfo = value;
    }

    /**
     * Gets the value of the roomInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RoomInfo }
     *     
     */
    public RoomInfo getRoomInfo() {
        return roomInfo;
    }

    /**
     * Sets the value of the roomInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomInfo }
     *     
     */
    public void setRoomInfo(RoomInfo value) {
        this.roomInfo = value;
    }

    /**
     * Gets the value of the roomType property.
     * 
     * @return
     *     possible object is
     *     {@link RoomType }
     *     
     */
    public RoomType getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomType }
     *     
     */
    public void setRoomType(RoomType value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the schoolCourseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolCourseInfo }
     *     
     */
    public SchoolCourseInfo getSchoolCourseInfo() {
        return schoolCourseInfo;
    }

    /**
     * Sets the value of the schoolCourseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolCourseInfo }
     *     
     */
    public void setSchoolCourseInfo(SchoolCourseInfo value) {
        this.schoolCourseInfo = value;
    }

    /**
     * Gets the value of the schoolInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolInfo }
     *     
     */
    public SchoolInfo getSchoolInfo() {
        return schoolInfo;
    }

    /**
     * Sets the value of the schoolInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolInfo }
     *     
     */
    public void setSchoolInfo(SchoolInfo value) {
        this.schoolInfo = value;
    }

    /**
     * Gets the value of the sectionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SectionInfo }
     *     
     */
    public SectionInfo getSectionInfo() {
        return sectionInfo;
    }

    /**
     * Sets the value of the sectionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SectionInfo }
     *     
     */
    public void setSectionInfo(SectionInfo value) {
        this.sectionInfo = value;
    }

    /**
     * Gets the value of the staffPersonal property.
     * 
     * @return
     *     possible object is
     *     {@link StaffPersonal }
     *     
     */
    public StaffPersonal getStaffPersonal() {
        return staffPersonal;
    }

    /**
     * Sets the value of the staffPersonal property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffPersonal }
     *     
     */
    public void setStaffPersonal(StaffPersonal value) {
        this.staffPersonal = value;
    }

    /**
     * Gets the value of the studentContact property.
     * 
     * @return
     *     possible object is
     *     {@link StudentContact }
     *     
     */
    public StudentContact getStudentContact() {
        return studentContact;
    }

    /**
     * Sets the value of the studentContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentContact }
     *     
     */
    public void setStudentContact(StudentContact value) {
        this.studentContact = value;
    }

    /**
     * Gets the value of the studentDailyAttendance property.
     * 
     * @return
     *     possible object is
     *     {@link StudentDailyAttendance }
     *     
     */
    public StudentDailyAttendance getStudentDailyAttendance() {
        return studentDailyAttendance;
    }

    /**
     * Sets the value of the studentDailyAttendance property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentDailyAttendance }
     *     
     */
    public void setStudentDailyAttendance(StudentDailyAttendance value) {
        this.studentDailyAttendance = value;
    }

    /**
     * Gets the value of the studentPersonal property.
     * 
     * @return
     *     possible object is
     *     {@link StudentPersonal }
     *     
     */
    public StudentPersonal getStudentPersonal() {
        return studentPersonal;
    }

    /**
     * Sets the value of the studentPersonal property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentPersonal }
     *     
     */
    public void setStudentPersonal(StudentPersonal value) {
        this.studentPersonal = value;
    }

    /**
     * Gets the value of the studentPicture property.
     * 
     * @return
     *     possible object is
     *     {@link StudentPicture }
     *     
     */
    public StudentPicture getStudentPicture() {
        return studentPicture;
    }

    /**
     * Sets the value of the studentPicture property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentPicture }
     *     
     */
    public void setStudentPicture(StudentPicture value) {
        this.studentPicture = value;
    }

    /**
     * Gets the value of the studentSchoolEnrollment property.
     * 
     * @return
     *     possible object is
     *     {@link StudentSchoolEnrollment }
     *     
     */
    public StudentSchoolEnrollment getStudentSchoolEnrollment() {
        return studentSchoolEnrollment;
    }

    /**
     * Sets the value of the studentSchoolEnrollment property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentSchoolEnrollment }
     *     
     */
    public void setStudentSchoolEnrollment(StudentSchoolEnrollment value) {
        this.studentSchoolEnrollment = value;
    }

    /**
     * Gets the value of the studentSectionEnrollment property.
     * 
     * @return
     *     possible object is
     *     {@link StudentSectionEnrollment }
     *     
     */
    public StudentSectionEnrollment getStudentSectionEnrollment() {
        return studentSectionEnrollment;
    }

    /**
     * Sets the value of the studentSectionEnrollment property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentSectionEnrollment }
     *     
     */
    public void setStudentSectionEnrollment(StudentSectionEnrollment value) {
        this.studentSectionEnrollment = value;
    }

    /**
     * Gets the value of the termInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TermInfo }
     *     
     */
    public TermInfo getTermInfo() {
        return termInfo;
    }

    /**
     * Sets the value of the termInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermInfo }
     *     
     */
    public void setTermInfo(TermInfo value) {
        this.termInfo = value;
    }

    /**
     * Gets the value of the leaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LEAInfo }
     *     
     */
    public LEAInfo getLEAInfo() {
        return leaInfo;
    }

    /**
     * Sets the value of the leaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEAInfo }
     *     
     */
    public void setLEAInfo(LEAInfo value) {
        this.leaInfo = value;
    }

    /**
     * Gets the value of the busEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link BusEquipment }
     *     
     */
    public BusEquipment getBusEquipment() {
        return busEquipment;
    }

    /**
     * Sets the value of the busEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusEquipment }
     *     
     */
    public void setBusEquipment(BusEquipment value) {
        this.busEquipment = value;
    }

    /**
     * Gets the value of the busInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BusInfo }
     *     
     */
    public BusInfo getBusInfo() {
        return busInfo;
    }

    /**
     * Sets the value of the busInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusInfo }
     *     
     */
    public void setBusInfo(BusInfo value) {
        this.busInfo = value;
    }

    /**
     * Gets the value of the busRouteDetail property.
     * 
     * @return
     *     possible object is
     *     {@link BusRouteDetail }
     *     
     */
    public BusRouteDetail getBusRouteDetail() {
        return busRouteDetail;
    }

    /**
     * Sets the value of the busRouteDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusRouteDetail }
     *     
     */
    public void setBusRouteDetail(BusRouteDetail value) {
        this.busRouteDetail = value;
    }

    /**
     * Gets the value of the busRouteInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BusRouteInfo }
     *     
     */
    public BusRouteInfo getBusRouteInfo() {
        return busRouteInfo;
    }

    /**
     * Sets the value of the busRouteInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusRouteInfo }
     *     
     */
    public void setBusRouteInfo(BusRouteInfo value) {
        this.busRouteInfo = value;
    }

    /**
     * Gets the value of the busStopInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BusStopInfo }
     *     
     */
    public BusStopInfo getBusStopInfo() {
        return busStopInfo;
    }

    /**
     * Sets the value of the busStopInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusStopInfo }
     *     
     */
    public void setBusStopInfo(BusStopInfo value) {
        this.busStopInfo = value;
    }

    /**
     * Gets the value of the studentTransportInfo property.
     * 
     * @return
     *     possible object is
     *     {@link StudentTransportInfo }
     *     
     */
    public StudentTransportInfo getStudentTransportInfo() {
        return studentTransportInfo;
    }

    /**
     * Sets the value of the studentTransportInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentTransportInfo }
     *     
     */
    public void setStudentTransportInfo(StudentTransportInfo value) {
        this.studentTransportInfo = value;
    }

    /**
     * Gets the value of the busPositionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BusPositionInfo }
     *     
     */
    public BusPositionInfo getBusPositionInfo() {
        return busPositionInfo;
    }

    /**
     * Sets the value of the busPositionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusPositionInfo }
     *     
     */
    public void setBusPositionInfo(BusPositionInfo value) {
        this.busPositionInfo = value;
    }

    /**
     * Gets the value of the reportManifest property.
     * 
     * @return
     *     possible object is
     *     {@link ReportManifest }
     *     
     */
    public ReportManifest getReportManifest() {
        return reportManifest;
    }

    /**
     * Sets the value of the reportManifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportManifest }
     *     
     */
    public void setReportManifest(ReportManifest value) {
        this.reportManifest = value;
    }

    /**
     * Gets the value of the reportAuthorityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ReportAuthorityInfo }
     *     
     */
    public ReportAuthorityInfo getReportAuthorityInfo() {
        return reportAuthorityInfo;
    }

    /**
     * Sets the value of the reportAuthorityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportAuthorityInfo }
     *     
     */
    public void setReportAuthorityInfo(ReportAuthorityInfo value) {
        this.reportAuthorityInfo = value;
    }

    /**
     * Gets the value of the sifReportObject property.
     * 
     * @return
     *     possible object is
     *     {@link SIFReportObject }
     *     
     */
    public SIFReportObject getSIFReportObject() {
        return sifReportObject;
    }

    /**
     * Sets the value of the sifReportObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFReportObject }
     *     
     */
    public void setSIFReportObject(SIFReportObject value) {
        this.sifReportObject = value;
    }

    /**
     * Gets the value of the sifLogEntry property.
     * 
     * @return
     *     possible object is
     *     {@link SIFLogEntry }
     *     
     */
    public SIFLogEntry getSIFLogEntry() {
        return sifLogEntry;
    }

    /**
     * Sets the value of the sifLogEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFLogEntry }
     *     
     */
    public void setSIFLogEntry(SIFLogEntry value) {
        this.sifLogEntry = value;
    }

    /**
     * Gets the value of the authentication property.
     * 
     * @return
     *     possible object is
     *     {@link Authentication }
     *     
     */
    public Authentication getAuthentication() {
        return authentication;
    }

    /**
     * Sets the value of the authentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authentication }
     *     
     */
    public void setAuthentication(Authentication value) {
        this.authentication = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribeObjectNames }
     *     
     */
    public SubscribeObjectNames getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribeObjectNames }
     *     
     */
    public void setObjectName(SubscribeObjectNames value) {
        this.objectName = value;
    }

}
