//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sifinfo.org/infrastructure/1.x}SIF_MessageType">
 *       &lt;sequence>
 *         &lt;element name="SIF_ObjectData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_EventObject"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sifObjectData"
})
@XmlRootElement(name = "SIF_Event")
public class SIFEvent
    extends SIFMessageType
{

    @XmlElement(name = "SIF_ObjectData", required = true)
    protected SIFEvent.SIFObjectData sifObjectData;

    /**
     * Gets the value of the sifObjectData property.
     * 
     * @return
     *     possible object is
     *     {@link SIFEvent.SIFObjectData }
     *     
     */
    public SIFEvent.SIFObjectData getSIFObjectData() {
        return sifObjectData;
    }

    /**
     * Sets the value of the sifObjectData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFEvent.SIFObjectData }
     *     
     */
    public void setSIFObjectData(SIFEvent.SIFObjectData value) {
        this.sifObjectData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_EventObject"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sifEventObject"
    })
    public static class SIFObjectData {

        @XmlElement(name = "SIF_EventObject", required = true)
        protected SIFEventObject sifEventObject;

        /**
         * Gets the value of the sifEventObject property.
         * 
         * @return
         *     possible object is
         *     {@link SIFEventObject }
         *     
         */
        public SIFEventObject getSIFEventObject() {
            return sifEventObject;
        }

        /**
         * Sets the value of the sifEventObject property.
         * 
         * @param value
         *     allowed object is
         *     {@link SIFEventObject }
         *     
         */
        public void setSIFEventObject(SIFEventObject value) {
            this.sifEventObject = value;
        }

    }

}
