//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Ack"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Event"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Provide"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Register"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Request"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Response"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Subscribe"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_SystemControl"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Unprovide"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Unregister"/>
 *         &lt;element ref="{http://www.sifinfo.org/infrastructure/1.x}SIF_Unsubscribe"/>
 *       &lt;/choice>
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sifAck",
    "sifEvent",
    "sifProvide",
    "sifRegister",
    "sifRequest",
    "sifResponse",
    "sifSubscribe",
    "sifSystemControl",
    "sifUnprovide",
    "sifUnregister",
    "sifUnsubscribe"
})
@XmlRootElement(name = "SIF_Message")
public class SIFMessage {

    @XmlElement(name = "SIF_Ack")
    protected SIFAck sifAck;
    @XmlElement(name = "SIF_Event")
    protected SIFEvent sifEvent;
    @XmlElement(name = "SIF_Provide")
    protected SIFProvide sifProvide;
    @XmlElement(name = "SIF_Register")
    protected SIFRegister sifRegister;
    @XmlElement(name = "SIF_Request")
    protected SIFRequest sifRequest;
    @XmlElement(name = "SIF_Response")
    protected SIFResponse sifResponse;
    @XmlElement(name = "SIF_Subscribe")
    protected SIFSubscribe sifSubscribe;
    @XmlElement(name = "SIF_SystemControl")
    protected SIFSystemControl sifSystemControl;
    @XmlElement(name = "SIF_Unprovide")
    protected SIFUnprovide sifUnprovide;
    @XmlElement(name = "SIF_Unregister")
    protected SIFUnregister sifUnregister;
    @XmlElement(name = "SIF_Unsubscribe")
    protected SIFUnsubscribe sifUnsubscribe;
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * Gets the value of the sifAck property.
     * 
     * @return
     *     possible object is
     *     {@link SIFAck }
     *     
     */
    public SIFAck getSIFAck() {
        return sifAck;
    }

    /**
     * Sets the value of the sifAck property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFAck }
     *     
     */
    public void setSIFAck(SIFAck value) {
        this.sifAck = value;
    }

    /**
     * Gets the value of the sifEvent property.
     * 
     * @return
     *     possible object is
     *     {@link SIFEvent }
     *     
     */
    public SIFEvent getSIFEvent() {
        return sifEvent;
    }

    /**
     * Sets the value of the sifEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFEvent }
     *     
     */
    public void setSIFEvent(SIFEvent value) {
        this.sifEvent = value;
    }

    /**
     * Gets the value of the sifProvide property.
     * 
     * @return
     *     possible object is
     *     {@link SIFProvide }
     *     
     */
    public SIFProvide getSIFProvide() {
        return sifProvide;
    }

    /**
     * Sets the value of the sifProvide property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFProvide }
     *     
     */
    public void setSIFProvide(SIFProvide value) {
        this.sifProvide = value;
    }

    /**
     * Gets the value of the sifRegister property.
     * 
     * @return
     *     possible object is
     *     {@link SIFRegister }
     *     
     */
    public SIFRegister getSIFRegister() {
        return sifRegister;
    }

    /**
     * Sets the value of the sifRegister property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFRegister }
     *     
     */
    public void setSIFRegister(SIFRegister value) {
        this.sifRegister = value;
    }

    /**
     * Gets the value of the sifRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SIFRequest }
     *     
     */
    public SIFRequest getSIFRequest() {
        return sifRequest;
    }

    /**
     * Sets the value of the sifRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFRequest }
     *     
     */
    public void setSIFRequest(SIFRequest value) {
        this.sifRequest = value;
    }

    /**
     * Gets the value of the sifResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SIFResponse }
     *     
     */
    public SIFResponse getSIFResponse() {
        return sifResponse;
    }

    /**
     * Sets the value of the sifResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFResponse }
     *     
     */
    public void setSIFResponse(SIFResponse value) {
        this.sifResponse = value;
    }

    /**
     * Gets the value of the sifSubscribe property.
     * 
     * @return
     *     possible object is
     *     {@link SIFSubscribe }
     *     
     */
    public SIFSubscribe getSIFSubscribe() {
        return sifSubscribe;
    }

    /**
     * Sets the value of the sifSubscribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFSubscribe }
     *     
     */
    public void setSIFSubscribe(SIFSubscribe value) {
        this.sifSubscribe = value;
    }

    /**
     * Gets the value of the sifSystemControl property.
     * 
     * @return
     *     possible object is
     *     {@link SIFSystemControl }
     *     
     */
    public SIFSystemControl getSIFSystemControl() {
        return sifSystemControl;
    }

    /**
     * Sets the value of the sifSystemControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFSystemControl }
     *     
     */
    public void setSIFSystemControl(SIFSystemControl value) {
        this.sifSystemControl = value;
    }

    /**
     * Gets the value of the sifUnprovide property.
     * 
     * @return
     *     possible object is
     *     {@link SIFUnprovide }
     *     
     */
    public SIFUnprovide getSIFUnprovide() {
        return sifUnprovide;
    }

    /**
     * Sets the value of the sifUnprovide property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFUnprovide }
     *     
     */
    public void setSIFUnprovide(SIFUnprovide value) {
        this.sifUnprovide = value;
    }

    /**
     * Gets the value of the sifUnregister property.
     * 
     * @return
     *     possible object is
     *     {@link SIFUnregister }
     *     
     */
    public SIFUnregister getSIFUnregister() {
        return sifUnregister;
    }

    /**
     * Sets the value of the sifUnregister property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFUnregister }
     *     
     */
    public void setSIFUnregister(SIFUnregister value) {
        this.sifUnregister = value;
    }

    /**
     * Gets the value of the sifUnsubscribe property.
     * 
     * @return
     *     possible object is
     *     {@link SIFUnsubscribe }
     *     
     */
    public SIFUnsubscribe getSIFUnsubscribe() {
        return sifUnsubscribe;
    }

    /**
     * Sets the value of the sifUnsubscribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIFUnsubscribe }
     *     
     */
    public void setSIFUnsubscribe(SIFUnsubscribe value) {
        this.sifUnsubscribe = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
