//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for SubscribeObjectNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SubscribeObjectNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AggregateStatisticInfo"/>
 *     &lt;enumeration value="AggregateCharacteristicInfo"/>
 *     &lt;enumeration value="AggregateStatisticFact"/>
 *     &lt;enumeration value="StudentMeal"/>
 *     &lt;enumeration value="FoodserviceItem"/>
 *     &lt;enumeration value="FoodserviceItemUnit"/>
 *     &lt;enumeration value="FoodserviceItemPortion"/>
 *     &lt;enumeration value="FoodserviceReimbursementRates"/>
 *     &lt;enumeration value="FoodserviceMealPrices"/>
 *     &lt;enumeration value="StaffMeal"/>
 *     &lt;enumeration value="FoodserviceTransaction"/>
 *     &lt;enumeration value="FoodserviceTransactionDetails"/>
 *     &lt;enumeration value="FoodserviceTransactionPayMethod"/>
 *     &lt;enumeration value="FoodserviceSales"/>
 *     &lt;enumeration value="FoodserviceItemSales"/>
 *     &lt;enumeration value="AccountingPeriod"/>
 *     &lt;enumeration value="FinancialAccount"/>
 *     &lt;enumeration value="FinancialAccountAccountingPeriodLocationInfo"/>
 *     &lt;enumeration value="FinancialClass"/>
 *     &lt;enumeration value="FinancialIncomeStatement"/>
 *     &lt;enumeration value="FinancialTransaction"/>
 *     &lt;enumeration value="FiscalYear"/>
 *     &lt;enumeration value="Billing"/>
 *     &lt;enumeration value="Payment"/>
 *     &lt;enumeration value="ActivityProvider"/>
 *     &lt;enumeration value="EmployeeAssignment"/>
 *     &lt;enumeration value="EmployeeContract"/>
 *     &lt;enumeration value="EmployeeCredit"/>
 *     &lt;enumeration value="EmployeeHR"/>
 *     &lt;enumeration value="EmployeePersonal"/>
 *     &lt;enumeration value="EmployeePicture"/>
 *     &lt;enumeration value="ProfDevActivities"/>
 *     &lt;enumeration value="StaffAssignment"/>
 *     &lt;enumeration value="TimeWorked"/>
 *     &lt;enumeration value="VendorInfo"/>
 *     &lt;enumeration value="W4"/>
 *     &lt;enumeration value="EmployeeWage"/>
 *     &lt;enumeration value="LocationInfo"/>
 *     &lt;enumeration value="Purchasing"/>
 *     &lt;enumeration value="LearningStandardDocument"/>
 *     &lt;enumeration value="LearningStandardItem"/>
 *     &lt;enumeration value="CurriculumStructure"/>
 *     &lt;enumeration value="Lesson"/>
 *     &lt;enumeration value="Activity"/>
 *     &lt;enumeration value="Assignment"/>
 *     &lt;enumeration value="Assessment"/>
 *     &lt;enumeration value="AssessmentSection"/>
 *     &lt;enumeration value="AssessmentItem"/>
 *     &lt;enumeration value="AssessmentSubTest"/>
 *     &lt;enumeration value="StudentResultSet"/>
 *     &lt;enumeration value="LearningResource"/>
 *     &lt;enumeration value="StudentParticipation"/>
 *     &lt;enumeration value="StudentPlacement"/>
 *     &lt;enumeration value="AttendanceCodeInfo"/>
 *     &lt;enumeration value="RoomInfo"/>
 *     &lt;enumeration value="RoomType"/>
 *     &lt;enumeration value="SchoolCourseInfo"/>
 *     &lt;enumeration value="SchoolInfo"/>
 *     &lt;enumeration value="SectionInfo"/>
 *     &lt;enumeration value="StaffPersonal"/>
 *     &lt;enumeration value="StudentContact"/>
 *     &lt;enumeration value="StudentDailyAttendance"/>
 *     &lt;enumeration value="StudentPersonal"/>
 *     &lt;enumeration value="StudentPicture"/>
 *     &lt;enumeration value="StudentSchoolEnrollment"/>
 *     &lt;enumeration value="StudentSectionEnrollment"/>
 *     &lt;enumeration value="TermInfo"/>
 *     &lt;enumeration value="LEAInfo"/>
 *     &lt;enumeration value="BusEquipment"/>
 *     &lt;enumeration value="BusInfo"/>
 *     &lt;enumeration value="BusRouteDetail"/>
 *     &lt;enumeration value="BusRouteInfo"/>
 *     &lt;enumeration value="BusStopInfo"/>
 *     &lt;enumeration value="StudentTransportInfo"/>
 *     &lt;enumeration value="BusPositionInfo"/>
 *     &lt;enumeration value="ReportManifest"/>
 *     &lt;enumeration value="ReportAuthorityInfo"/>
 *     &lt;enumeration value="SIF_ReportObject"/>
 *     &lt;enumeration value="SIF_LogEntry"/>
 *     &lt;enumeration value="Authentication"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum SubscribeObjectNames {

    @XmlEnumValue("AccountingPeriod")
    ACCOUNTING_PERIOD("AccountingPeriod"),
    @XmlEnumValue("Activity")
    ACTIVITY("Activity"),
    @XmlEnumValue("ActivityProvider")
    ACTIVITY_PROVIDER("ActivityProvider"),
    @XmlEnumValue("AggregateCharacteristicInfo")
    AGGREGATE_CHARACTERISTIC_INFO("AggregateCharacteristicInfo"),
    @XmlEnumValue("AggregateStatisticFact")
    AGGREGATE_STATISTIC_FACT("AggregateStatisticFact"),
    @XmlEnumValue("AggregateStatisticInfo")
    AGGREGATE_STATISTIC_INFO("AggregateStatisticInfo"),
    @XmlEnumValue("Assessment")
    ASSESSMENT("Assessment"),
    @XmlEnumValue("AssessmentItem")
    ASSESSMENT_ITEM("AssessmentItem"),
    @XmlEnumValue("AssessmentSection")
    ASSESSMENT_SECTION("AssessmentSection"),
    @XmlEnumValue("AssessmentSubTest")
    ASSESSMENT_SUB_TEST("AssessmentSubTest"),
    @XmlEnumValue("Assignment")
    ASSIGNMENT("Assignment"),
    @XmlEnumValue("AttendanceCodeInfo")
    ATTENDANCE_CODE_INFO("AttendanceCodeInfo"),
    @XmlEnumValue("Authentication")
    AUTHENTICATION("Authentication"),
    @XmlEnumValue("Billing")
    BILLING("Billing"),
    @XmlEnumValue("BusEquipment")
    BUS_EQUIPMENT("BusEquipment"),
    @XmlEnumValue("BusInfo")
    BUS_INFO("BusInfo"),
    @XmlEnumValue("BusPositionInfo")
    BUS_POSITION_INFO("BusPositionInfo"),
    @XmlEnumValue("BusRouteDetail")
    BUS_ROUTE_DETAIL("BusRouteDetail"),
    @XmlEnumValue("BusRouteInfo")
    BUS_ROUTE_INFO("BusRouteInfo"),
    @XmlEnumValue("BusStopInfo")
    BUS_STOP_INFO("BusStopInfo"),
    @XmlEnumValue("CurriculumStructure")
    CURRICULUM_STRUCTURE("CurriculumStructure"),
    @XmlEnumValue("EmployeeAssignment")
    EMPLOYEE_ASSIGNMENT("EmployeeAssignment"),
    @XmlEnumValue("EmployeeContract")
    EMPLOYEE_CONTRACT("EmployeeContract"),
    @XmlEnumValue("EmployeeCredit")
    EMPLOYEE_CREDIT("EmployeeCredit"),
    @XmlEnumValue("EmployeeHR")
    EMPLOYEE_HR("EmployeeHR"),
    @XmlEnumValue("EmployeePersonal")
    EMPLOYEE_PERSONAL("EmployeePersonal"),
    @XmlEnumValue("EmployeePicture")
    EMPLOYEE_PICTURE("EmployeePicture"),
    @XmlEnumValue("EmployeeWage")
    EMPLOYEE_WAGE("EmployeeWage"),
    @XmlEnumValue("FinancialAccount")
    FINANCIAL_ACCOUNT("FinancialAccount"),
    @XmlEnumValue("FinancialAccountAccountingPeriodLocationInfo")
    FINANCIAL_ACCOUNT_ACCOUNTING_PERIOD_LOCATION_INFO("FinancialAccountAccountingPeriodLocationInfo"),
    @XmlEnumValue("FinancialClass")
    FINANCIAL_CLASS("FinancialClass"),
    @XmlEnumValue("FinancialIncomeStatement")
    FINANCIAL_INCOME_STATEMENT("FinancialIncomeStatement"),
    @XmlEnumValue("FinancialTransaction")
    FINANCIAL_TRANSACTION("FinancialTransaction"),
    @XmlEnumValue("FiscalYear")
    FISCAL_YEAR("FiscalYear"),
    @XmlEnumValue("FoodserviceItem")
    FOODSERVICE_ITEM("FoodserviceItem"),
    @XmlEnumValue("FoodserviceItemPortion")
    FOODSERVICE_ITEM_PORTION("FoodserviceItemPortion"),
    @XmlEnumValue("FoodserviceItemSales")
    FOODSERVICE_ITEM_SALES("FoodserviceItemSales"),
    @XmlEnumValue("FoodserviceItemUnit")
    FOODSERVICE_ITEM_UNIT("FoodserviceItemUnit"),
    @XmlEnumValue("FoodserviceMealPrices")
    FOODSERVICE_MEAL_PRICES("FoodserviceMealPrices"),
    @XmlEnumValue("FoodserviceReimbursementRates")
    FOODSERVICE_REIMBURSEMENT_RATES("FoodserviceReimbursementRates"),
    @XmlEnumValue("FoodserviceSales")
    FOODSERVICE_SALES("FoodserviceSales"),
    @XmlEnumValue("FoodserviceTransaction")
    FOODSERVICE_TRANSACTION("FoodserviceTransaction"),
    @XmlEnumValue("FoodserviceTransactionDetails")
    FOODSERVICE_TRANSACTION_DETAILS("FoodserviceTransactionDetails"),
    @XmlEnumValue("FoodserviceTransactionPayMethod")
    FOODSERVICE_TRANSACTION_PAY_METHOD("FoodserviceTransactionPayMethod"),
    @XmlEnumValue("LearningResource")
    LEARNING_RESOURCE("LearningResource"),
    @XmlEnumValue("LearningStandardDocument")
    LEARNING_STANDARD_DOCUMENT("LearningStandardDocument"),
    @XmlEnumValue("LearningStandardItem")
    LEARNING_STANDARD_ITEM("LearningStandardItem"),
    @XmlEnumValue("LEAInfo")
    LEA_INFO("LEAInfo"),
    @XmlEnumValue("Lesson")
    LESSON("Lesson"),
    @XmlEnumValue("LocationInfo")
    LOCATION_INFO("LocationInfo"),
    @XmlEnumValue("Payment")
    PAYMENT("Payment"),
    @XmlEnumValue("ProfDevActivities")
    PROF_DEV_ACTIVITIES("ProfDevActivities"),
    @XmlEnumValue("Purchasing")
    PURCHASING("Purchasing"),
    @XmlEnumValue("ReportAuthorityInfo")
    REPORT_AUTHORITY_INFO("ReportAuthorityInfo"),
    @XmlEnumValue("ReportManifest")
    REPORT_MANIFEST("ReportManifest"),
    @XmlEnumValue("RoomInfo")
    ROOM_INFO("RoomInfo"),
    @XmlEnumValue("RoomType")
    ROOM_TYPE("RoomType"),
    @XmlEnumValue("SchoolCourseInfo")
    SCHOOL_COURSE_INFO("SchoolCourseInfo"),
    @XmlEnumValue("SchoolInfo")
    SCHOOL_INFO("SchoolInfo"),
    @XmlEnumValue("SectionInfo")
    SECTION_INFO("SectionInfo"),
    @XmlEnumValue("SIF_LogEntry")
    SIF_LOG_ENTRY("SIF_LogEntry"),
    @XmlEnumValue("SIF_ReportObject")
    SIF_REPORT_OBJECT("SIF_ReportObject"),
    @XmlEnumValue("StaffAssignment")
    STAFF_ASSIGNMENT("StaffAssignment"),
    @XmlEnumValue("StaffMeal")
    STAFF_MEAL("StaffMeal"),
    @XmlEnumValue("StaffPersonal")
    STAFF_PERSONAL("StaffPersonal"),
    @XmlEnumValue("StudentContact")
    STUDENT_CONTACT("StudentContact"),
    @XmlEnumValue("StudentDailyAttendance")
    STUDENT_DAILY_ATTENDANCE("StudentDailyAttendance"),
    @XmlEnumValue("StudentMeal")
    STUDENT_MEAL("StudentMeal"),
    @XmlEnumValue("StudentParticipation")
    STUDENT_PARTICIPATION("StudentParticipation"),
    @XmlEnumValue("StudentPersonal")
    STUDENT_PERSONAL("StudentPersonal"),
    @XmlEnumValue("StudentPicture")
    STUDENT_PICTURE("StudentPicture"),
    @XmlEnumValue("StudentPlacement")
    STUDENT_PLACEMENT("StudentPlacement"),
    @XmlEnumValue("StudentResultSet")
    STUDENT_RESULT_SET("StudentResultSet"),
    @XmlEnumValue("StudentSchoolEnrollment")
    STUDENT_SCHOOL_ENROLLMENT("StudentSchoolEnrollment"),
    @XmlEnumValue("StudentSectionEnrollment")
    STUDENT_SECTION_ENROLLMENT("StudentSectionEnrollment"),
    @XmlEnumValue("StudentTransportInfo")
    STUDENT_TRANSPORT_INFO("StudentTransportInfo"),
    @XmlEnumValue("TermInfo")
    TERM_INFO("TermInfo"),
    @XmlEnumValue("TimeWorked")
    TIME_WORKED("TimeWorked"),
    @XmlEnumValue("VendorInfo")
    VENDOR_INFO("VendorInfo"),
    @XmlEnumValue("W4")
    W_4("W4");
    private final String value;

    SubscribeObjectNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubscribeObjectNames fromValue(String v) {
        for (SubscribeObjectNames c: SubscribeObjectNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
