//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.07 at 09:44:38 PM MST 
//


package com.uvasoftware.core.primitives;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="DisembarkBusRouteDetailRefId" use="required" type="{http://www.sifinfo.org/infrastructure/1.x}RefIdOrEmptyType" />
 *       &lt;attribute name="EmbarkBusRouteDetailRefId" use="required" type="{http://www.sifinfo.org/infrastructure/1.x}RefIdOrEmptyType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "TransferPoint")
public class TransferPoint {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "DisembarkBusRouteDetailRefId", required = true)
    protected String disembarkBusRouteDetailRefId;
    @XmlAttribute(name = "EmbarkBusRouteDetailRefId", required = true)
    protected String embarkBusRouteDetailRefId;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the disembarkBusRouteDetailRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisembarkBusRouteDetailRefId() {
        return disembarkBusRouteDetailRefId;
    }

    /**
     * Sets the value of the disembarkBusRouteDetailRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisembarkBusRouteDetailRefId(String value) {
        this.disembarkBusRouteDetailRefId = value;
    }

    /**
     * Gets the value of the embarkBusRouteDetailRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmbarkBusRouteDetailRefId() {
        return embarkBusRouteDetailRefId;
    }

    /**
     * Sets the value of the embarkBusRouteDetailRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmbarkBusRouteDetailRefId(String value) {
        this.embarkBusRouteDetailRefId = value;
    }

}
